#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Simulation script for COMPONENT: myproject

cd /home/li/bambuhls
verilator --cc --exe --Mdir /home/li/bambuhls/HLS_output//verilator_beh/verilator_obj -Wno-fatal -Wno-lint -sv -O3 --x-assign fast --x-initial fast --noassert -LDFLAGS -static /home/li/bambuhls/myproject.v /home/li/bambuhls/HLS_output//simulation/testbench_myproject_main.cpp /home/li/bambuhls/HLS_output//simulation/testbench_myproject_tb.v --top-module myproject_tb
if [ $? -ne 0 ]; then
   exit 1;
fi


ln -s /home/li/bambuhls/HLS_output/ /home/li/bambuhls/HLS_output//verilator_beh/verilator_obj
make -C /home/li/bambuhls/HLS_output//verilator_beh/verilator_obj -j OPT="-fstrict-aliasing" -f Vmyproject_tb.mk Vmyproject_tb

/home/li/bambuhls/HLS_output//verilator_beh/verilator_obj/Vmyproject_tb 2>&1 | tee /home/li/bambuhls/HLS_output//verilator_beh/myproject_verilator.log

cat /home/li/bambuhls/HLS_output//verilator_beh/myproject_verilator.log


