// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [255:0] data_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;

reg   [12:0] trunc_ln_reg_16369;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] trunc_ln708_1_reg_16374;
reg   [15:0] trunc_ln708_2_reg_16379;
reg   [15:0] trunc_ln708_3_reg_16384;
reg   [14:0] trunc_ln708_4_reg_16389;
reg   [11:0] trunc_ln708_5_reg_16394;
reg   [15:0] trunc_ln708_6_reg_16399;
reg   [15:0] trunc_ln708_7_reg_16404;
reg   [11:0] trunc_ln708_8_reg_16409;
reg   [13:0] trunc_ln708_9_reg_16414;
reg   [15:0] trunc_ln708_s_reg_16419;
reg   [14:0] trunc_ln708_10_reg_16424;
reg   [15:0] trunc_ln708_11_reg_16429;
reg   [15:0] trunc_ln708_12_reg_16434;
reg   [15:0] trunc_ln708_13_reg_16439;
reg   [15:0] trunc_ln708_14_reg_16444;
reg   [15:0] trunc_ln708_15_reg_16449;
reg   [14:0] trunc_ln708_16_reg_16454;
reg   [15:0] trunc_ln708_17_reg_16459;
reg   [15:0] trunc_ln708_18_reg_16464;
reg   [15:0] trunc_ln708_19_reg_16469;
reg   [15:0] trunc_ln708_20_reg_16474;
reg   [15:0] trunc_ln708_21_reg_16479;
reg   [14:0] trunc_ln708_22_reg_16484;
reg   [12:0] trunc_ln708_23_reg_16489;
reg   [15:0] trunc_ln708_24_reg_16494;
reg   [15:0] trunc_ln708_25_reg_16499;
reg   [15:0] trunc_ln708_26_reg_16504;
reg   [15:0] trunc_ln708_27_reg_16509;
reg   [14:0] trunc_ln708_28_reg_16514;
reg   [12:0] trunc_ln708_29_reg_16519;
reg   [14:0] trunc_ln708_30_reg_16524;
reg   [15:0] trunc_ln708_31_reg_16529;
reg   [14:0] trunc_ln708_32_reg_16534;
reg   [15:0] trunc_ln708_33_reg_16539;
reg   [15:0] trunc_ln708_34_reg_16544;
reg   [15:0] trunc_ln708_35_reg_16549;
reg   [15:0] trunc_ln708_36_reg_16554;
reg   [7:0] trunc_ln708_37_reg_16559;
reg   [15:0] trunc_ln708_38_reg_16564;
reg   [15:0] trunc_ln708_39_reg_16569;
reg   [15:0] trunc_ln708_40_reg_16574;
reg   [15:0] trunc_ln708_41_reg_16579;
reg   [11:0] trunc_ln708_42_reg_16584;
reg   [11:0] trunc_ln708_43_reg_16589;
reg   [14:0] trunc_ln708_44_reg_16594;
reg   [13:0] trunc_ln708_45_reg_16599;
reg   [14:0] trunc_ln708_46_reg_16604;
reg   [15:0] trunc_ln708_47_reg_16609;
reg   [15:0] trunc_ln708_48_reg_16614;
reg   [15:0] trunc_ln708_49_reg_16619;
reg   [15:0] trunc_ln708_50_reg_16624;
reg   [15:0] trunc_ln708_51_reg_16629;
reg   [15:0] trunc_ln708_52_reg_16634;
reg   [15:0] trunc_ln708_53_reg_16639;
reg   [15:0] trunc_ln708_54_reg_16644;
reg   [15:0] trunc_ln708_55_reg_16649;
reg   [9:0] trunc_ln708_56_reg_16654;
reg   [14:0] trunc_ln708_57_reg_16659;
reg   [11:0] trunc_ln708_58_reg_16664;
reg   [15:0] trunc_ln708_59_reg_16669;
reg   [14:0] trunc_ln708_60_reg_16674;
reg   [13:0] trunc_ln708_61_reg_16679;
reg   [15:0] trunc_ln708_62_reg_16684;
wire   [15:0] add_ln703_2_fu_16056_p2;
reg   [15:0] add_ln703_2_reg_16689;
wire   [15:0] add_ln703_5_fu_16071_p2;
reg   [15:0] add_ln703_5_reg_16694;
wire   [15:0] add_ln703_7_fu_16077_p2;
reg   [15:0] add_ln703_7_reg_16699;
wire   [15:0] add_ln703_8_fu_16081_p2;
reg   [15:0] add_ln703_8_reg_16704;
wire   [15:0] add_ln703_12_fu_16094_p2;
reg   [15:0] add_ln703_12_reg_16709;
wire   [15:0] add_ln703_17_fu_16110_p2;
reg   [15:0] add_ln703_17_reg_16714;
wire   [15:0] add_ln703_20_fu_16126_p2;
reg   [15:0] add_ln703_20_reg_16719;
wire   [15:0] add_ln703_22_fu_16132_p2;
reg   [15:0] add_ln703_22_reg_16724;
wire   [15:0] add_ln703_23_fu_16137_p2;
reg   [15:0] add_ln703_23_reg_16729;
wire   [15:0] add_ln703_27_fu_16152_p2;
reg   [15:0] add_ln703_27_reg_16734;
wire   [15:0] add_ln703_32_fu_16166_p2;
reg   [15:0] add_ln703_32_reg_16739;
wire   [15:0] add_ln703_35_fu_16181_p2;
reg   [15:0] add_ln703_35_reg_16744;
wire   [15:0] add_ln703_37_fu_16187_p2;
reg   [15:0] add_ln703_37_reg_16749;
wire   [15:0] add_ln703_38_fu_16192_p2;
reg   [15:0] add_ln703_38_reg_16754;
wire   [15:0] add_ln703_42_fu_16207_p2;
reg   [15:0] add_ln703_42_reg_16759;
wire   [15:0] add_ln703_47_fu_16222_p2;
reg   [15:0] add_ln703_47_reg_16764;
wire   [15:0] add_ln703_50_fu_16238_p2;
reg   [15:0] add_ln703_50_reg_16769;
wire   [15:0] add_ln703_52_fu_16244_p2;
reg   [15:0] add_ln703_52_reg_16774;
wire   [15:0] add_ln703_53_fu_16248_p2;
reg   [15:0] add_ln703_53_reg_16779;
wire   [15:0] add_ln703_57_fu_16263_p2;
reg   [15:0] add_ln703_57_reg_16784;
wire  signed [15:0] mul_ln1118_3_fu_262_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] mul_ln1118_2_fu_263_p1;
wire  signed [25:0] sext_ln1118_fu_14796_p1;
wire  signed [15:0] mul_ln1118_33_fu_264_p1;
wire  signed [25:0] sext_ln1118_26_fu_15489_p1;
wire  signed [15:0] mul_ln1118_42_fu_265_p1;
wire  signed [25:0] sext_ln1118_33_fu_15705_p1;
wire  signed [15:0] mul_ln1118_1_fu_267_p1;
wire  signed [15:0] mul_ln1118_31_fu_268_p1;
wire  signed [15:0] mul_ln1118_29_fu_269_p1;
wire  signed [25:0] sext_ln1118_25_fu_15432_p1;
wire  signed [15:0] mul_ln1118_21_fu_270_p1;
wire  signed [25:0] sext_ln1118_19_fu_15299_p1;
wire  signed [15:0] mul_ln1118_43_fu_271_p1;
wire  signed [15:0] mul_ln1118_4_fu_272_p1;
wire  signed [25:0] sext_ln1118_3_fu_14883_p1;
wire  signed [15:0] mul_ln1118_26_fu_273_p1;
wire  signed [24:0] sext_ln1118_22_fu_15366_p1;
wire  signed [15:0] mul_ln1118_32_fu_274_p1;
wire  signed [15:0] mul_ln1118_fu_275_p1;
wire  signed [15:0] mul_ln1118_40_fu_276_p1;
wire  signed [24:0] sext_ln1118_31_fu_15644_p1;
wire  signed [15:0] mul_ln1118_5_fu_277_p1;
wire  signed [15:0] mul_ln1118_23_fu_278_p1;
wire  signed [15:0] mul_ln1118_49_fu_279_p1;
wire  signed [15:0] mul_ln1118_36_fu_280_p1;
wire  signed [25:0] sext_ln1118_28_fu_15564_p1;
wire  signed [15:0] mul_ln1118_37_fu_281_p1;
wire  signed [15:0] mul_ln1118_52_fu_284_p1;
wire  signed [15:0] mul_ln1118_50_fu_285_p1;
wire  signed [15:0] mul_ln1118_18_fu_286_p1;
wire  signed [15:0] mul_ln1118_48_fu_287_p1;
wire  signed [25:0] sext_ln1118_34_fu_15763_p1;
wire  signed [15:0] mul_ln1118_39_fu_288_p1;
wire  signed [15:0] mul_ln1118_53_fu_290_p1;
wire  signed [15:0] mul_ln1118_28_fu_291_p1;
wire  signed [15:0] mul_ln1118_13_fu_292_p1;
wire  signed [25:0] sext_ln1118_16_fu_15180_p1;
wire  signed [15:0] mul_ln1118_35_fu_293_p1;
wire  signed [15:0] mul_ln1118_12_fu_295_p1;
wire  signed [15:0] mul_ln1118_24_fu_296_p1;
wire  signed [15:0] mul_ln1118_20_fu_297_p1;
wire  signed [15:0] mul_ln1118_22_fu_298_p1;
wire  signed [15:0] mul_ln1118_11_fu_300_p1;
wire  signed [15:0] mul_ln1118_17_fu_301_p1;
wire  signed [25:0] sext_ln1118_18_fu_15242_p1;
wire  signed [15:0] mul_ln1118_19_fu_303_p1;
wire  signed [15:0] mul_ln1118_54_fu_304_p1;
wire  signed [25:0] sext_ln1118_41_fu_15927_p1;
wire  signed [15:0] mul_ln1118_27_fu_306_p1;
wire  signed [15:0] mul_ln1118_15_fu_307_p1;
wire  signed [15:0] mul_ln1118_10_fu_308_p1;
wire  signed [25:0] sext_ln1118_12_fu_15088_p1;
wire  signed [15:0] mul_ln1118_16_fu_310_p1;
wire  signed [15:0] mul_ln1118_47_fu_311_p1;
wire  signed [15:0] mul_ln1118_14_fu_312_p1;
wire  signed [15:0] mul_ln1118_30_fu_313_p1;
wire  signed [15:0] mul_ln1118_46_fu_314_p1;
wire  signed [15:0] mul_ln1118_41_fu_315_p1;
wire  signed [15:0] mul_ln1118_25_fu_316_p1;
wire  signed [15:0] mul_ln1118_7_fu_317_p1;
wire  signed [15:0] mul_ln1118_8_fu_318_p1;
wire  signed [15:0] mul_ln1118_45_fu_319_p1;
wire  signed [15:0] mul_ln1118_51_fu_320_p1;
wire  signed [15:0] mul_ln1118_9_fu_321_p1;
wire  signed [15:0] mul_ln1118_34_fu_322_p1;
wire  signed [15:0] mul_ln1118_44_fu_323_p1;
wire  signed [15:0] mul_ln1118_38_fu_324_p1;
wire  signed [15:0] mul_ln1118_6_fu_325_p1;
wire  signed [15:0] trunc_ln203_fu_14792_p1;
wire   [21:0] shl_ln_fu_14803_p3;
wire   [16:0] shl_ln1118_1_fu_14815_p3;
wire  signed [22:0] sext_ln1118_1_fu_14811_p1;
wire  signed [22:0] sext_ln1118_2_fu_14823_p1;
wire   [22:0] sub_ln1118_fu_14827_p2;
wire   [25:0] mul_ln1118_fu_275_p2;
wire   [25:0] mul_ln1118_1_fu_267_p2;
wire   [25:0] mul_ln1118_2_fu_263_p2;
wire  signed [15:0] tmp_2_fu_14873_p4;
wire   [24:0] mul_ln1118_3_fu_262_p2;
wire   [20:0] shl_ln1118_2_fu_14904_p3;
wire   [16:0] shl_ln1118_3_fu_14916_p3;
wire  signed [21:0] sext_ln1118_6_fu_14924_p1;
wire  signed [21:0] sext_ln1118_5_fu_14912_p1;
wire   [21:0] add_ln1118_fu_14928_p2;
wire   [25:0] mul_ln1118_4_fu_272_p2;
wire   [25:0] mul_ln1118_5_fu_277_p2;
wire  signed [15:0] tmp_3_fu_14964_p4;
wire   [20:0] shl_ln1118_4_fu_14984_p3;
wire  signed [21:0] sext_ln1118_9_fu_14992_p1;
wire   [16:0] shl_ln1118_5_fu_15002_p3;
wire   [21:0] sub_ln1118_1_fu_14996_p2;
wire  signed [21:0] sext_ln1118_10_fu_15010_p1;
wire   [21:0] sub_ln1118_2_fu_15014_p2;
wire   [22:0] shl_ln1118_6_fu_15030_p3;
wire  signed [23:0] sext_ln1118_11_fu_15038_p1;
wire   [23:0] sub_ln1118_3_fu_15042_p2;
wire   [25:0] mul_ln1118_6_fu_325_p2;
wire   [24:0] mul_ln1118_7_fu_317_p2;
wire  signed [15:0] tmp_4_fu_15078_p4;
wire   [25:0] mul_ln1118_8_fu_318_p2;
wire   [25:0] mul_ln1118_9_fu_321_p2;
wire   [25:0] mul_ln1118_10_fu_308_p2;
wire   [24:0] shl_ln1118_7_fu_15125_p3;
wire   [17:0] shl_ln1118_8_fu_15137_p3;
wire  signed [25:0] sext_ln1118_14_fu_15145_p1;
wire  signed [25:0] sext_ln1118_13_fu_15133_p1;
wire   [25:0] add_ln1118_1_fu_15149_p2;
wire  signed [15:0] tmp_5_fu_15165_p4;
wire   [25:0] mul_ln1118_11_fu_300_p2;
wire   [24:0] mul_ln1118_12_fu_295_p2;
wire   [25:0] mul_ln1118_13_fu_292_p2;
wire   [25:0] mul_ln1118_14_fu_312_p2;
wire  signed [15:0] tmp_6_fu_15227_p4;
wire   [25:0] mul_ln1118_15_fu_307_p2;
wire   [25:0] mul_ln1118_16_fu_310_p2;
wire   [25:0] mul_ln1118_17_fu_301_p2;
wire   [24:0] mul_ln1118_18_fu_286_p2;
wire  signed [15:0] tmp_7_fu_15289_p4;
wire   [22:0] mul_ln1118_19_fu_303_p2;
wire   [25:0] mul_ln1118_20_fu_297_p2;
wire   [25:0] mul_ln1118_21_fu_270_p2;
wire   [25:0] mul_ln1118_22_fu_298_p2;
wire  signed [15:0] tmp_8_fu_15351_p4;
wire   [25:0] mul_ln1118_23_fu_278_p2;
wire   [24:0] mul_ln1118_24_fu_296_p2;
wire   [22:0] mul_ln1118_25_fu_316_p2;
wire   [24:0] mul_ln1118_26_fu_273_p2;
wire  signed [15:0] tmp_9_fu_15417_p4;
wire   [25:0] mul_ln1118_27_fu_306_p2;
wire   [24:0] mul_ln1118_28_fu_291_p2;
wire   [25:0] mul_ln1118_29_fu_269_p2;
wire   [25:0] mul_ln1118_30_fu_313_p2;
wire  signed [15:0] tmp_s_fu_15479_p4;
wire   [25:0] mul_ln1118_31_fu_268_p2;
wire   [25:0] mul_ln1118_32_fu_274_p2;
wire   [16:0] shl_ln1118_9_fu_15516_p3;
wire  signed [17:0] sext_ln1118_27_fu_15524_p1;
wire   [17:0] sub_ln1118_4_fu_15528_p2;
wire   [25:0] mul_ln1118_33_fu_264_p2;
wire  signed [15:0] tmp_1_fu_15554_p4;
wire   [25:0] mul_ln1118_34_fu_322_p2;
wire   [25:0] mul_ln1118_35_fu_293_p2;
wire   [25:0] mul_ln1118_36_fu_280_p2;
wire   [20:0] shl_ln1118_s_fu_15601_p3;
wire  signed [21:0] sext_ln1118_29_fu_15609_p1;
wire   [21:0] sub_ln1118_5_fu_15613_p2;
wire  signed [15:0] tmp_10_fu_15629_p4;
wire   [21:0] mul_ln1118_37_fu_281_p2;
wire   [24:0] mul_ln1118_38_fu_324_p2;
wire   [23:0] mul_ln1118_39_fu_288_p2;
wire   [24:0] mul_ln1118_40_fu_276_p2;
wire   [15:0] tmp_11_fu_15695_p4;
wire   [25:0] mul_ln1118_41_fu_315_p2;
wire   [25:0] mul_ln1118_42_fu_265_p2;
wire   [25:0] mul_ln1118_43_fu_271_p2;
wire   [25:0] mul_ln1118_44_fu_323_p2;
wire   [15:0] tmp_12_fu_15753_p4;
wire   [25:0] mul_ln1118_45_fu_319_p2;
wire   [25:0] mul_ln1118_46_fu_314_p2;
wire   [25:0] mul_ln1118_47_fu_311_p2;
wire   [25:0] mul_ln1118_48_fu_287_p2;
wire  signed [15:0] tmp_13_fu_15811_p4;
wire   [25:0] mul_ln1118_49_fu_279_p2;
wire   [18:0] shl_ln1118_10_fu_15841_p3;
wire  signed [19:0] sext_ln1118_37_fu_15849_p1;
wire   [19:0] sub_ln1118_6_fu_15853_p2;
wire   [24:0] mul_ln1118_50_fu_285_p2;
wire   [20:0] shl_ln1118_11_fu_15879_p3;
wire  signed [21:0] sext_ln1118_38_fu_15887_p1;
wire   [21:0] sub_ln1118_7_fu_15891_p2;
wire  signed [15:0] tmp_14_fu_15907_p4;
wire   [25:0] mul_ln1118_51_fu_320_p2;
wire   [24:0] mul_ln1118_52_fu_284_p2;
wire   [23:0] mul_ln1118_53_fu_290_p2;
wire   [25:0] mul_ln1118_54_fu_304_p2;
wire  signed [15:0] sext_ln708_fu_15973_p1;
wire  signed [15:0] sext_ln708_1_fu_15976_p1;
wire  signed [15:0] sext_ln708_3_fu_15982_p1;
wire   [15:0] add_ln703_1_fu_16051_p2;
wire   [15:0] add_ln703_fu_16045_p2;
wire  signed [15:0] sext_ln708_8_fu_15997_p1;
wire   [15:0] add_ln703_4_fu_16066_p2;
wire   [15:0] add_ln703_3_fu_16062_p2;
wire  signed [15:0] sext_ln708_15_fu_16018_p1;
wire   [15:0] add_ln703_11_fu_16090_p2;
wire   [15:0] add_ln703_10_fu_16086_p2;
wire  signed [15:0] sext_ln708_2_fu_15979_p1;
wire  signed [15:0] sext_ln708_4_fu_15985_p1;
wire   [15:0] add_ln703_16_fu_16105_p2;
wire   [15:0] add_ln703_15_fu_16100_p2;
wire  signed [15:0] sext_ln708_6_fu_15991_p1;
wire  signed [15:0] sext_ln708_9_fu_16000_p1;
wire   [15:0] add_ln703_19_fu_16121_p2;
wire   [15:0] add_ln703_18_fu_16116_p2;
wire  signed [15:0] sext_ln708_12_fu_16009_p1;
wire  signed [15:0] sext_ln708_16_fu_16021_p1;
wire  signed [15:0] sext_ln708_19_fu_16030_p1;
wire  signed [15:0] sext_ln708_22_fu_16039_p1;
wire   [15:0] add_ln703_26_fu_16146_p2;
wire   [15:0] add_ln703_25_fu_16142_p2;
wire   [15:0] add_ln703_31_fu_16162_p2;
wire   [15:0] add_ln703_30_fu_16158_p2;
wire  signed [15:0] sext_ln708_10_fu_16003_p1;
wire   [15:0] add_ln703_34_fu_16176_p2;
wire   [15:0] add_ln703_33_fu_16172_p2;
wire  signed [15:0] sext_ln708_13_fu_16012_p1;
wire  signed [15:0] sext_ln708_17_fu_16024_p1;
wire  signed [15:0] sext_ln708_20_fu_16033_p1;
wire  signed [15:0] sext_ln708_23_fu_16042_p1;
wire   [15:0] add_ln703_41_fu_16201_p2;
wire   [15:0] add_ln703_40_fu_16197_p2;
wire  signed [15:0] sext_ln708_5_fu_15988_p1;
wire   [15:0] add_ln703_46_fu_16217_p2;
wire   [15:0] add_ln703_45_fu_16213_p2;
wire  signed [15:0] sext_ln708_7_fu_15994_p1;
wire  signed [15:0] sext_ln708_11_fu_16006_p1;
wire   [15:0] add_ln703_49_fu_16233_p2;
wire   [15:0] add_ln703_48_fu_16228_p2;
wire  signed [15:0] sext_ln708_14_fu_16015_p1;
wire  signed [15:0] sext_ln708_18_fu_16027_p1;
wire  signed [15:0] sext_ln708_21_fu_16036_p1;
wire   [15:0] add_ln703_56_fu_16258_p2;
wire   [15:0] add_ln703_55_fu_16254_p2;
wire   [15:0] add_ln703_9_fu_16273_p2;
wire   [15:0] add_ln703_13_fu_16277_p2;
wire   [15:0] add_ln703_6_fu_16269_p2;
wire   [15:0] add_ln703_24_fu_16292_p2;
wire   [15:0] add_ln703_28_fu_16296_p2;
wire   [15:0] add_ln703_21_fu_16288_p2;
wire   [15:0] add_ln703_39_fu_16311_p2;
wire   [15:0] add_ln703_43_fu_16315_p2;
wire   [15:0] add_ln703_36_fu_16307_p2;
wire   [15:0] add_ln703_54_fu_16330_p2;
wire   [15:0] add_ln703_58_fu_16334_p2;
wire   [15:0] add_ln703_51_fu_16326_p2;
wire   [15:0] add_ln703_14_fu_16282_p2;
wire   [15:0] acc_1_V_fu_16301_p2;
wire   [15:0] acc_2_V_fu_16320_p2;
wire   [15:0] acc_3_V_fu_16339_p2;
reg    ap_ce_reg;
reg   [255:0] data_V_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln703_12_reg_16709 <= add_ln703_12_fu_16094_p2;
        add_ln703_17_reg_16714 <= add_ln703_17_fu_16110_p2;
        add_ln703_20_reg_16719 <= add_ln703_20_fu_16126_p2;
        add_ln703_22_reg_16724 <= add_ln703_22_fu_16132_p2;
        add_ln703_23_reg_16729 <= add_ln703_23_fu_16137_p2;
        add_ln703_27_reg_16734 <= add_ln703_27_fu_16152_p2;
        add_ln703_2_reg_16689 <= add_ln703_2_fu_16056_p2;
        add_ln703_32_reg_16739 <= add_ln703_32_fu_16166_p2;
        add_ln703_35_reg_16744 <= add_ln703_35_fu_16181_p2;
        add_ln703_37_reg_16749 <= add_ln703_37_fu_16187_p2;
        add_ln703_38_reg_16754 <= add_ln703_38_fu_16192_p2;
        add_ln703_42_reg_16759 <= add_ln703_42_fu_16207_p2;
        add_ln703_47_reg_16764 <= add_ln703_47_fu_16222_p2;
        add_ln703_50_reg_16769 <= add_ln703_50_fu_16238_p2;
        add_ln703_52_reg_16774 <= add_ln703_52_fu_16244_p2;
        add_ln703_53_reg_16779 <= add_ln703_53_fu_16248_p2;
        add_ln703_57_reg_16784 <= add_ln703_57_fu_16263_p2;
        add_ln703_5_reg_16694 <= add_ln703_5_fu_16071_p2;
        add_ln703_7_reg_16699 <= add_ln703_7_fu_16077_p2;
        add_ln703_8_reg_16704 <= add_ln703_8_fu_16081_p2;
        trunc_ln708_10_reg_16424 <= {{mul_ln1118_7_fu_317_p2[24:10]}};
        trunc_ln708_11_reg_16429 <= {{mul_ln1118_8_fu_318_p2[25:10]}};
        trunc_ln708_12_reg_16434 <= {{mul_ln1118_9_fu_321_p2[25:10]}};
        trunc_ln708_13_reg_16439 <= {{mul_ln1118_10_fu_308_p2[25:10]}};
        trunc_ln708_14_reg_16444 <= {{add_ln1118_1_fu_15149_p2[25:10]}};
        trunc_ln708_15_reg_16449 <= {{mul_ln1118_11_fu_300_p2[25:10]}};
        trunc_ln708_16_reg_16454 <= {{mul_ln1118_12_fu_295_p2[24:10]}};
        trunc_ln708_17_reg_16459 <= {{mul_ln1118_13_fu_292_p2[25:10]}};
        trunc_ln708_18_reg_16464 <= {{mul_ln1118_14_fu_312_p2[25:10]}};
        trunc_ln708_19_reg_16469 <= {{mul_ln1118_15_fu_307_p2[25:10]}};
        trunc_ln708_1_reg_16374 <= {{mul_ln1118_fu_275_p2[25:10]}};
        trunc_ln708_20_reg_16474 <= {{mul_ln1118_16_fu_310_p2[25:10]}};
        trunc_ln708_21_reg_16479 <= {{mul_ln1118_17_fu_301_p2[25:10]}};
        trunc_ln708_22_reg_16484 <= {{mul_ln1118_18_fu_286_p2[24:10]}};
        trunc_ln708_23_reg_16489 <= {{mul_ln1118_19_fu_303_p2[22:10]}};
        trunc_ln708_24_reg_16494 <= {{mul_ln1118_20_fu_297_p2[25:10]}};
        trunc_ln708_25_reg_16499 <= {{mul_ln1118_21_fu_270_p2[25:10]}};
        trunc_ln708_26_reg_16504 <= {{mul_ln1118_22_fu_298_p2[25:10]}};
        trunc_ln708_27_reg_16509 <= {{mul_ln1118_23_fu_278_p2[25:10]}};
        trunc_ln708_28_reg_16514 <= {{mul_ln1118_24_fu_296_p2[24:10]}};
        trunc_ln708_29_reg_16519 <= {{mul_ln1118_25_fu_316_p2[22:10]}};
        trunc_ln708_2_reg_16379 <= {{mul_ln1118_1_fu_267_p2[25:10]}};
        trunc_ln708_30_reg_16524 <= {{mul_ln1118_26_fu_273_p2[24:10]}};
        trunc_ln708_31_reg_16529 <= {{mul_ln1118_27_fu_306_p2[25:10]}};
        trunc_ln708_32_reg_16534 <= {{mul_ln1118_28_fu_291_p2[24:10]}};
        trunc_ln708_33_reg_16539 <= {{mul_ln1118_29_fu_269_p2[25:10]}};
        trunc_ln708_34_reg_16544 <= {{mul_ln1118_30_fu_313_p2[25:10]}};
        trunc_ln708_35_reg_16549 <= {{mul_ln1118_31_fu_268_p2[25:10]}};
        trunc_ln708_36_reg_16554 <= {{mul_ln1118_32_fu_274_p2[25:10]}};
        trunc_ln708_37_reg_16559 <= {{sub_ln1118_4_fu_15528_p2[17:10]}};
        trunc_ln708_38_reg_16564 <= {{mul_ln1118_33_fu_264_p2[25:10]}};
        trunc_ln708_39_reg_16569 <= {{mul_ln1118_34_fu_322_p2[25:10]}};
        trunc_ln708_3_reg_16384 <= {{mul_ln1118_2_fu_263_p2[25:10]}};
        trunc_ln708_40_reg_16574 <= {{mul_ln1118_35_fu_293_p2[25:10]}};
        trunc_ln708_41_reg_16579 <= {{mul_ln1118_36_fu_280_p2[25:10]}};
        trunc_ln708_42_reg_16584 <= {{sub_ln1118_5_fu_15613_p2[21:10]}};
        trunc_ln708_43_reg_16589 <= {{mul_ln1118_37_fu_281_p2[21:10]}};
        trunc_ln708_44_reg_16594 <= {{mul_ln1118_38_fu_324_p2[24:10]}};
        trunc_ln708_45_reg_16599 <= {{mul_ln1118_39_fu_288_p2[23:10]}};
        trunc_ln708_46_reg_16604 <= {{mul_ln1118_40_fu_276_p2[24:10]}};
        trunc_ln708_47_reg_16609 <= {{mul_ln1118_41_fu_315_p2[25:10]}};
        trunc_ln708_48_reg_16614 <= {{mul_ln1118_42_fu_265_p2[25:10]}};
        trunc_ln708_49_reg_16619 <= {{mul_ln1118_43_fu_271_p2[25:10]}};
        trunc_ln708_4_reg_16389 <= {{mul_ln1118_3_fu_262_p2[24:10]}};
        trunc_ln708_50_reg_16624 <= {{mul_ln1118_44_fu_323_p2[25:10]}};
        trunc_ln708_51_reg_16629 <= {{mul_ln1118_45_fu_319_p2[25:10]}};
        trunc_ln708_52_reg_16634 <= {{mul_ln1118_46_fu_314_p2[25:10]}};
        trunc_ln708_53_reg_16639 <= {{mul_ln1118_47_fu_311_p2[25:10]}};
        trunc_ln708_54_reg_16644 <= {{mul_ln1118_48_fu_287_p2[25:10]}};
        trunc_ln708_55_reg_16649 <= {{mul_ln1118_49_fu_279_p2[25:10]}};
        trunc_ln708_56_reg_16654 <= {{sub_ln1118_6_fu_15853_p2[19:10]}};
        trunc_ln708_57_reg_16659 <= {{mul_ln1118_50_fu_285_p2[24:10]}};
        trunc_ln708_58_reg_16664 <= {{sub_ln1118_7_fu_15891_p2[21:10]}};
        trunc_ln708_59_reg_16669 <= {{mul_ln1118_51_fu_320_p2[25:10]}};
        trunc_ln708_5_reg_16394 <= {{add_ln1118_fu_14928_p2[21:10]}};
        trunc_ln708_60_reg_16674 <= {{mul_ln1118_52_fu_284_p2[24:10]}};
        trunc_ln708_61_reg_16679 <= {{mul_ln1118_53_fu_290_p2[23:10]}};
        trunc_ln708_62_reg_16684 <= {{mul_ln1118_54_fu_304_p2[25:10]}};
        trunc_ln708_6_reg_16399 <= {{mul_ln1118_4_fu_272_p2[25:10]}};
        trunc_ln708_7_reg_16404 <= {{mul_ln1118_5_fu_277_p2[25:10]}};
        trunc_ln708_8_reg_16409 <= {{sub_ln1118_2_fu_15014_p2[21:10]}};
        trunc_ln708_9_reg_16414 <= {{sub_ln1118_3_fu_15042_p2[23:10]}};
        trunc_ln708_s_reg_16419 <= {{mul_ln1118_6_fu_325_p2[25:10]}};
        trunc_ln_reg_16369 <= {{sub_ln1118_fu_14827_p2[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_14_fu_16282_p2;
        ap_return_1_int_reg <= acc_1_V_fu_16301_p2;
        ap_return_2_int_reg <= acc_2_V_fu_16320_p2;
        ap_return_3_int_reg <= acc_3_V_fu_16339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_V_read_int_reg <= data_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_14_fu_16282_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = acc_1_V_fu_16301_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = acc_2_V_fu_16320_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = acc_3_V_fu_16339_p2;
    end
end

assign acc_1_V_fu_16301_p2 = (add_ln703_28_fu_16296_p2 + add_ln703_21_fu_16288_p2);

assign acc_2_V_fu_16320_p2 = (add_ln703_43_fu_16315_p2 + add_ln703_36_fu_16307_p2);

assign acc_3_V_fu_16339_p2 = (add_ln703_58_fu_16334_p2 + add_ln703_51_fu_16326_p2);

assign add_ln1118_1_fu_15149_p2 = ($signed(sext_ln1118_14_fu_15145_p1) + $signed(sext_ln1118_13_fu_15133_p1));

assign add_ln1118_fu_14928_p2 = ($signed(sext_ln1118_6_fu_14924_p1) + $signed(sext_ln1118_5_fu_14912_p1));

assign add_ln703_10_fu_16086_p2 = (trunc_ln708_47_reg_16609 + trunc_ln708_51_reg_16629);

assign add_ln703_11_fu_16090_p2 = (trunc_ln708_55_reg_16649 + trunc_ln708_59_reg_16669);

assign add_ln703_12_fu_16094_p2 = (add_ln703_11_fu_16090_p2 + add_ln703_10_fu_16086_p2);

assign add_ln703_13_fu_16277_p2 = (add_ln703_12_reg_16709 + add_ln703_9_fu_16273_p2);

assign add_ln703_14_fu_16282_p2 = (add_ln703_13_fu_16277_p2 + add_ln703_6_fu_16269_p2);

assign add_ln703_15_fu_16100_p2 = ($signed(trunc_ln708_1_reg_16374) + $signed(sext_ln708_2_fu_15979_p1));

assign add_ln703_16_fu_16105_p2 = ($signed(sext_ln708_4_fu_15985_p1) + $signed(trunc_ln708_12_reg_16434));

assign add_ln703_17_fu_16110_p2 = (add_ln703_16_fu_16105_p2 + add_ln703_15_fu_16100_p2);

assign add_ln703_18_fu_16116_p2 = ($signed(sext_ln708_6_fu_15991_p1) + $signed(trunc_ln708_20_reg_16474));

assign add_ln703_19_fu_16121_p2 = ($signed(trunc_ln708_24_reg_16494) + $signed(sext_ln708_9_fu_16000_p1));

assign add_ln703_1_fu_16051_p2 = ($signed(sext_ln708_3_fu_15982_p1) + $signed(trunc_ln708_11_reg_16429));

assign add_ln703_20_fu_16126_p2 = (add_ln703_19_fu_16121_p2 + add_ln703_18_fu_16116_p2);

assign add_ln703_21_fu_16288_p2 = (add_ln703_20_reg_16719 + add_ln703_17_reg_16714);

assign add_ln703_22_fu_16132_p2 = ($signed(sext_ln708_12_fu_16009_p1) + $signed(trunc_ln708_36_reg_16554));

assign add_ln703_23_fu_16137_p2 = ($signed(trunc_ln708_40_reg_16574) + $signed(sext_ln708_16_fu_16021_p1));

assign add_ln703_24_fu_16292_p2 = (add_ln703_23_reg_16729 + add_ln703_22_reg_16724);

assign add_ln703_25_fu_16142_p2 = (trunc_ln708_48_reg_16614 + trunc_ln708_52_reg_16634);

assign add_ln703_26_fu_16146_p2 = ($signed(sext_ln708_19_fu_16030_p1) + $signed(sext_ln708_22_fu_16039_p1));

assign add_ln703_27_fu_16152_p2 = (add_ln703_26_fu_16146_p2 + add_ln703_25_fu_16142_p2);

assign add_ln703_28_fu_16296_p2 = (add_ln703_27_reg_16734 + add_ln703_24_fu_16292_p2);

assign add_ln703_2_fu_16056_p2 = (add_ln703_1_fu_16051_p2 + add_ln703_fu_16045_p2);

assign add_ln703_30_fu_16158_p2 = (trunc_ln708_2_reg_16379 + trunc_ln708_6_reg_16399);

assign add_ln703_31_fu_16162_p2 = (trunc_ln708_s_reg_16419 + trunc_ln708_13_reg_16439);

assign add_ln703_32_fu_16166_p2 = (add_ln703_31_fu_16162_p2 + add_ln703_30_fu_16158_p2);

assign add_ln703_33_fu_16172_p2 = (trunc_ln708_17_reg_16459 + trunc_ln708_21_reg_16479);

assign add_ln703_34_fu_16176_p2 = ($signed(trunc_ln708_25_reg_16499) + $signed(sext_ln708_10_fu_16003_p1));

assign add_ln703_35_fu_16181_p2 = (add_ln703_34_fu_16176_p2 + add_ln703_33_fu_16172_p2);

assign add_ln703_36_fu_16307_p2 = (add_ln703_35_reg_16744 + add_ln703_32_reg_16739);

assign add_ln703_37_fu_16187_p2 = ($signed(trunc_ln708_33_reg_16539) + $signed(sext_ln708_13_fu_16012_p1));

assign add_ln703_38_fu_16192_p2 = ($signed(trunc_ln708_41_reg_16579) + $signed(sext_ln708_17_fu_16024_p1));

assign add_ln703_39_fu_16311_p2 = (add_ln703_38_reg_16754 + add_ln703_37_reg_16749);

assign add_ln703_3_fu_16062_p2 = (trunc_ln708_15_reg_16449 + trunc_ln708_19_reg_16469);

assign add_ln703_40_fu_16197_p2 = (trunc_ln708_49_reg_16619 + trunc_ln708_53_reg_16639);

assign add_ln703_41_fu_16201_p2 = ($signed(sext_ln708_20_fu_16033_p1) + $signed(sext_ln708_23_fu_16042_p1));

assign add_ln703_42_fu_16207_p2 = (add_ln703_41_fu_16201_p2 + add_ln703_40_fu_16197_p2);

assign add_ln703_43_fu_16315_p2 = (add_ln703_42_reg_16759 + add_ln703_39_fu_16311_p2);

assign add_ln703_45_fu_16213_p2 = (trunc_ln708_3_reg_16384 + trunc_ln708_7_reg_16404);

assign add_ln703_46_fu_16217_p2 = ($signed(sext_ln708_5_fu_15988_p1) + $signed(trunc_ln708_14_reg_16444));

assign add_ln703_47_fu_16222_p2 = (add_ln703_46_fu_16217_p2 + add_ln703_45_fu_16213_p2);

assign add_ln703_48_fu_16228_p2 = ($signed(trunc_ln708_18_reg_16464) + $signed(sext_ln708_7_fu_15994_p1));

assign add_ln703_49_fu_16233_p2 = ($signed(trunc_ln708_26_reg_16504) + $signed(sext_ln708_11_fu_16006_p1));

assign add_ln703_4_fu_16066_p2 = ($signed(sext_ln708_8_fu_15997_p1) + $signed(trunc_ln708_27_reg_16509));

assign add_ln703_50_fu_16238_p2 = (add_ln703_49_fu_16233_p2 + add_ln703_48_fu_16228_p2);

assign add_ln703_51_fu_16326_p2 = (add_ln703_50_reg_16769 + add_ln703_47_reg_16764);

assign add_ln703_52_fu_16244_p2 = (trunc_ln708_34_reg_16544 + trunc_ln708_38_reg_16564);

assign add_ln703_53_fu_16248_p2 = ($signed(sext_ln708_14_fu_16015_p1) + $signed(sext_ln708_18_fu_16027_p1));

assign add_ln703_54_fu_16330_p2 = (add_ln703_53_reg_16779 + add_ln703_52_reg_16774);

assign add_ln703_55_fu_16254_p2 = (trunc_ln708_50_reg_16624 + trunc_ln708_54_reg_16644);

assign add_ln703_56_fu_16258_p2 = ($signed(sext_ln708_21_fu_16036_p1) + $signed(trunc_ln708_62_reg_16684));

assign add_ln703_57_fu_16263_p2 = (add_ln703_56_fu_16258_p2 + add_ln703_55_fu_16254_p2);

assign add_ln703_58_fu_16334_p2 = (add_ln703_57_reg_16784 + add_ln703_54_fu_16330_p2);

assign add_ln703_5_fu_16071_p2 = (add_ln703_4_fu_16066_p2 + add_ln703_3_fu_16062_p2);

assign add_ln703_6_fu_16269_p2 = (add_ln703_5_reg_16694 + add_ln703_2_reg_16689);

assign add_ln703_7_fu_16077_p2 = (trunc_ln708_31_reg_16529 + trunc_ln708_35_reg_16549);

assign add_ln703_8_fu_16081_p2 = ($signed(trunc_ln708_39_reg_16569) + $signed(sext_ln708_15_fu_16018_p1));

assign add_ln703_9_fu_16273_p2 = (add_ln703_8_reg_16704 + add_ln703_7_reg_16699);

assign add_ln703_fu_16045_p2 = ($signed(sext_ln708_fu_15973_p1) + $signed(sext_ln708_1_fu_15976_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign mul_ln1118_10_fu_308_p1 = sext_ln1118_12_fu_15088_p1;

assign mul_ln1118_10_fu_308_p2 = ($signed(26'd67108424) * $signed(mul_ln1118_10_fu_308_p1));

assign mul_ln1118_11_fu_300_p1 = sext_ln1118_16_fu_15180_p1;

assign mul_ln1118_11_fu_300_p2 = ($signed(26'd67108540) * $signed(mul_ln1118_11_fu_300_p1));

assign mul_ln1118_12_fu_295_p1 = tmp_5_fu_15165_p4;

assign mul_ln1118_12_fu_295_p2 = ($signed({{1'b0}, {25'd182}}) * $signed(mul_ln1118_12_fu_295_p1));

assign mul_ln1118_13_fu_292_p1 = sext_ln1118_16_fu_15180_p1;

assign mul_ln1118_13_fu_292_p2 = ($signed(26'd67108438) * $signed(mul_ln1118_13_fu_292_p1));

assign mul_ln1118_14_fu_312_p1 = sext_ln1118_16_fu_15180_p1;

assign mul_ln1118_14_fu_312_p2 = ($signed(26'd67108470) * $signed(mul_ln1118_14_fu_312_p1));

assign mul_ln1118_15_fu_307_p1 = sext_ln1118_18_fu_15242_p1;

assign mul_ln1118_15_fu_307_p2 = ($signed({{1'b0}, {26'd546}}) * $signed(mul_ln1118_15_fu_307_p1));

assign mul_ln1118_16_fu_310_p1 = sext_ln1118_18_fu_15242_p1;

assign mul_ln1118_16_fu_310_p2 = ($signed({{1'b0}, {26'd386}}) * $signed(mul_ln1118_16_fu_310_p1));

assign mul_ln1118_17_fu_301_p1 = sext_ln1118_18_fu_15242_p1;

assign mul_ln1118_17_fu_301_p2 = ($signed(26'd67108373) * $signed(mul_ln1118_17_fu_301_p1));

assign mul_ln1118_18_fu_286_p1 = tmp_6_fu_15227_p4;

assign mul_ln1118_18_fu_286_p2 = ($signed({{1'b0}, {25'd176}}) * $signed(mul_ln1118_18_fu_286_p1));

assign mul_ln1118_19_fu_303_p1 = tmp_7_fu_15289_p4;

assign mul_ln1118_19_fu_303_p2 = ($signed(23'd8388564) * $signed(mul_ln1118_19_fu_303_p1));

assign mul_ln1118_1_fu_267_p1 = sext_ln1118_fu_14796_p1;

assign mul_ln1118_1_fu_267_p2 = ($signed({{1'b0}, {26'd409}}) * $signed(mul_ln1118_1_fu_267_p1));

assign mul_ln1118_20_fu_297_p1 = sext_ln1118_19_fu_15299_p1;

assign mul_ln1118_20_fu_297_p2 = ($signed({{1'b0}, {26'd542}}) * $signed(mul_ln1118_20_fu_297_p1));

assign mul_ln1118_21_fu_270_p1 = sext_ln1118_19_fu_15299_p1;

assign mul_ln1118_21_fu_270_p2 = ($signed({{1'b0}, {26'd437}}) * $signed(mul_ln1118_21_fu_270_p1));

assign mul_ln1118_22_fu_298_p1 = sext_ln1118_19_fu_15299_p1;

assign mul_ln1118_22_fu_298_p2 = ($signed({{1'b0}, {26'd298}}) * $signed(mul_ln1118_22_fu_298_p1));

assign mul_ln1118_23_fu_278_p1 = tmp_8_fu_15351_p4;

assign mul_ln1118_23_fu_278_p2 = ($signed({{1'b0}, {26'd281}}) * $signed(mul_ln1118_23_fu_278_p1));

assign mul_ln1118_24_fu_296_p1 = sext_ln1118_22_fu_15366_p1;

assign mul_ln1118_24_fu_296_p2 = ($signed(25'd33554203) * $signed(mul_ln1118_24_fu_296_p1));

assign mul_ln1118_25_fu_316_p1 = tmp_8_fu_15351_p4;

assign mul_ln1118_25_fu_316_p2 = ($signed(23'd8388562) * $signed(mul_ln1118_25_fu_316_p1));

assign mul_ln1118_26_fu_273_p1 = sext_ln1118_22_fu_15366_p1;

assign mul_ln1118_26_fu_273_p2 = ($signed({{1'b0}, {25'd200}}) * $signed(mul_ln1118_26_fu_273_p1));

assign mul_ln1118_27_fu_306_p1 = sext_ln1118_25_fu_15432_p1;

assign mul_ln1118_27_fu_306_p2 = ($signed(26'd67108591) * $signed(mul_ln1118_27_fu_306_p1));

assign mul_ln1118_28_fu_291_p1 = tmp_9_fu_15417_p4;

assign mul_ln1118_28_fu_291_p2 = ($signed({{1'b0}, {25'd177}}) * $signed(mul_ln1118_28_fu_291_p1));

assign mul_ln1118_29_fu_269_p1 = sext_ln1118_25_fu_15432_p1;

assign mul_ln1118_29_fu_269_p2 = ($signed({{1'b0}, {26'd318}}) * $signed(mul_ln1118_29_fu_269_p1));

assign mul_ln1118_2_fu_263_p1 = sext_ln1118_fu_14796_p1;

assign mul_ln1118_2_fu_263_p2 = ($signed({{1'b0}, {26'd311}}) * $signed(mul_ln1118_2_fu_263_p1));

assign mul_ln1118_30_fu_313_p1 = sext_ln1118_25_fu_15432_p1;

assign mul_ln1118_30_fu_313_p2 = ($signed({{1'b0}, {26'd548}}) * $signed(mul_ln1118_30_fu_313_p1));

assign mul_ln1118_31_fu_268_p1 = sext_ln1118_26_fu_15489_p1;

assign mul_ln1118_31_fu_268_p2 = ($signed(26'd67108545) * $signed(mul_ln1118_31_fu_268_p1));

assign mul_ln1118_32_fu_274_p1 = sext_ln1118_26_fu_15489_p1;

assign mul_ln1118_32_fu_274_p2 = ($signed(26'd67108322) * $signed(mul_ln1118_32_fu_274_p1));

assign mul_ln1118_33_fu_264_p1 = sext_ln1118_26_fu_15489_p1;

assign mul_ln1118_33_fu_264_p2 = ($signed(26'd67108412) * $signed(mul_ln1118_33_fu_264_p1));

assign mul_ln1118_34_fu_322_p1 = sext_ln1118_28_fu_15564_p1;

assign mul_ln1118_34_fu_322_p2 = ($signed({{1'b0}, {26'd525}}) * $signed(mul_ln1118_34_fu_322_p1));

assign mul_ln1118_35_fu_293_p1 = sext_ln1118_28_fu_15564_p1;

assign mul_ln1118_35_fu_293_p2 = ($signed({{1'b0}, {26'd400}}) * $signed(mul_ln1118_35_fu_293_p1));

assign mul_ln1118_36_fu_280_p1 = sext_ln1118_28_fu_15564_p1;

assign mul_ln1118_36_fu_280_p2 = ($signed({{1'b0}, {26'd401}}) * $signed(mul_ln1118_36_fu_280_p1));

assign mul_ln1118_37_fu_281_p1 = tmp_10_fu_15629_p4;

assign mul_ln1118_37_fu_281_p2 = ($signed({{1'b0}, {22'd27}}) * $signed(mul_ln1118_37_fu_281_p1));

assign mul_ln1118_38_fu_324_p1 = sext_ln1118_31_fu_15644_p1;

assign mul_ln1118_38_fu_324_p2 = ($signed({{1'b0}, {25'd210}}) * $signed(mul_ln1118_38_fu_324_p1));

assign mul_ln1118_39_fu_288_p1 = tmp_10_fu_15629_p4;

assign mul_ln1118_39_fu_288_p2 = ($signed({{1'b0}, {24'd95}}) * $signed(mul_ln1118_39_fu_288_p1));

assign mul_ln1118_3_fu_262_p1 = tmp_2_fu_14873_p4;

assign mul_ln1118_3_fu_262_p2 = ($signed({{1'b0}, {25'd162}}) * $signed(mul_ln1118_3_fu_262_p1));

assign mul_ln1118_40_fu_276_p1 = sext_ln1118_31_fu_15644_p1;

assign mul_ln1118_40_fu_276_p2 = ($signed({{1'b0}, {25'd251}}) * $signed(mul_ln1118_40_fu_276_p1));

assign mul_ln1118_41_fu_315_p1 = sext_ln1118_33_fu_15705_p1;

assign mul_ln1118_41_fu_315_p2 = ($signed(26'd67108362) * $signed(mul_ln1118_41_fu_315_p1));

assign mul_ln1118_42_fu_265_p1 = sext_ln1118_33_fu_15705_p1;

assign mul_ln1118_42_fu_265_p2 = ($signed(26'd67108565) * $signed(mul_ln1118_42_fu_265_p1));

assign mul_ln1118_43_fu_271_p1 = sext_ln1118_33_fu_15705_p1;

assign mul_ln1118_43_fu_271_p2 = ($signed({{1'b0}, {26'd547}}) * $signed(mul_ln1118_43_fu_271_p1));

assign mul_ln1118_44_fu_323_p1 = sext_ln1118_33_fu_15705_p1;

assign mul_ln1118_44_fu_323_p2 = ($signed(26'd67108464) * $signed(mul_ln1118_44_fu_323_p1));

assign mul_ln1118_45_fu_319_p1 = sext_ln1118_34_fu_15763_p1;

assign mul_ln1118_45_fu_319_p2 = ($signed({{1'b0}, {26'd436}}) * $signed(mul_ln1118_45_fu_319_p1));

assign mul_ln1118_46_fu_314_p1 = sext_ln1118_34_fu_15763_p1;

assign mul_ln1118_46_fu_314_p2 = ($signed({{1'b0}, {26'd301}}) * $signed(mul_ln1118_46_fu_314_p1));

assign mul_ln1118_47_fu_311_p1 = sext_ln1118_34_fu_15763_p1;

assign mul_ln1118_47_fu_311_p2 = ($signed(26'd67108591) * $signed(mul_ln1118_47_fu_311_p1));

assign mul_ln1118_48_fu_287_p1 = sext_ln1118_34_fu_15763_p1;

assign mul_ln1118_48_fu_287_p2 = ($signed(26'd67108319) * $signed(mul_ln1118_48_fu_287_p1));

assign mul_ln1118_49_fu_279_p1 = tmp_13_fu_15811_p4;

assign mul_ln1118_49_fu_279_p2 = ($signed({{1'b0}, {26'd331}}) * $signed(mul_ln1118_49_fu_279_p1));

assign mul_ln1118_4_fu_272_p1 = sext_ln1118_3_fu_14883_p1;

assign mul_ln1118_4_fu_272_p2 = ($signed(26'd67108319) * $signed(mul_ln1118_4_fu_272_p1));

assign mul_ln1118_50_fu_285_p1 = tmp_13_fu_15811_p4;

assign mul_ln1118_50_fu_285_p2 = ($signed({{1'b0}, {25'd231}}) * $signed(mul_ln1118_50_fu_285_p1));

assign mul_ln1118_51_fu_320_p1 = sext_ln1118_41_fu_15927_p1;

assign mul_ln1118_51_fu_320_p2 = ($signed({{1'b0}, {26'd271}}) * $signed(mul_ln1118_51_fu_320_p1));

assign mul_ln1118_52_fu_284_p1 = tmp_14_fu_15907_p4;

assign mul_ln1118_52_fu_284_p2 = ($signed(25'd33554236) * $signed(mul_ln1118_52_fu_284_p1));

assign mul_ln1118_53_fu_290_p1 = tmp_14_fu_15907_p4;

assign mul_ln1118_53_fu_290_p2 = ($signed(24'd16777147) * $signed(mul_ln1118_53_fu_290_p1));

assign mul_ln1118_54_fu_304_p1 = sext_ln1118_41_fu_15927_p1;

assign mul_ln1118_54_fu_304_p2 = ($signed(26'd67108550) * $signed(mul_ln1118_54_fu_304_p1));

assign mul_ln1118_5_fu_277_p1 = sext_ln1118_3_fu_14883_p1;

assign mul_ln1118_5_fu_277_p2 = ($signed({{1'b0}, {26'd418}}) * $signed(mul_ln1118_5_fu_277_p1));

assign mul_ln1118_6_fu_325_p1 = tmp_3_fu_14964_p4;

assign mul_ln1118_6_fu_325_p2 = ($signed({{1'b0}, {26'd433}}) * $signed(mul_ln1118_6_fu_325_p1));

assign mul_ln1118_7_fu_317_p1 = tmp_3_fu_14964_p4;

assign mul_ln1118_7_fu_317_p2 = ($signed({{1'b0}, {25'd153}}) * $signed(mul_ln1118_7_fu_317_p1));

assign mul_ln1118_8_fu_318_p1 = sext_ln1118_12_fu_15088_p1;

assign mul_ln1118_8_fu_318_p2 = ($signed(26'd67108305) * $signed(mul_ln1118_8_fu_318_p1));

assign mul_ln1118_9_fu_321_p1 = sext_ln1118_12_fu_15088_p1;

assign mul_ln1118_9_fu_321_p2 = ($signed({{1'b0}, {26'd401}}) * $signed(mul_ln1118_9_fu_321_p1));

assign mul_ln1118_fu_275_p1 = sext_ln1118_fu_14796_p1;

assign mul_ln1118_fu_275_p2 = ($signed(26'd67108551) * $signed(mul_ln1118_fu_275_p1));

assign sext_ln1118_10_fu_15010_p1 = $signed(shl_ln1118_5_fu_15002_p3);

assign sext_ln1118_11_fu_15038_p1 = $signed(shl_ln1118_6_fu_15030_p3);

assign sext_ln1118_12_fu_15088_p1 = tmp_4_fu_15078_p4;

assign sext_ln1118_13_fu_15133_p1 = $signed(shl_ln1118_7_fu_15125_p3);

assign sext_ln1118_14_fu_15145_p1 = $signed(shl_ln1118_8_fu_15137_p3);

assign sext_ln1118_16_fu_15180_p1 = tmp_5_fu_15165_p4;

assign sext_ln1118_18_fu_15242_p1 = tmp_6_fu_15227_p4;

assign sext_ln1118_19_fu_15299_p1 = tmp_7_fu_15289_p4;

assign sext_ln1118_1_fu_14811_p1 = $signed(shl_ln_fu_14803_p3);

assign sext_ln1118_22_fu_15366_p1 = tmp_8_fu_15351_p4;

assign sext_ln1118_25_fu_15432_p1 = tmp_9_fu_15417_p4;

assign sext_ln1118_26_fu_15489_p1 = tmp_s_fu_15479_p4;

assign sext_ln1118_27_fu_15524_p1 = $signed(shl_ln1118_9_fu_15516_p3);

assign sext_ln1118_28_fu_15564_p1 = tmp_1_fu_15554_p4;

assign sext_ln1118_29_fu_15609_p1 = $signed(shl_ln1118_s_fu_15601_p3);

assign sext_ln1118_2_fu_14823_p1 = $signed(shl_ln1118_1_fu_14815_p3);

assign sext_ln1118_31_fu_15644_p1 = tmp_10_fu_15629_p4;

assign sext_ln1118_33_fu_15705_p1 = $signed(tmp_11_fu_15695_p4);

assign sext_ln1118_34_fu_15763_p1 = $signed(tmp_12_fu_15753_p4);

assign sext_ln1118_37_fu_15849_p1 = $signed(shl_ln1118_10_fu_15841_p3);

assign sext_ln1118_38_fu_15887_p1 = $signed(shl_ln1118_11_fu_15879_p3);

assign sext_ln1118_3_fu_14883_p1 = tmp_2_fu_14873_p4;

assign sext_ln1118_41_fu_15927_p1 = tmp_14_fu_15907_p4;

assign sext_ln1118_5_fu_14912_p1 = $signed(shl_ln1118_2_fu_14904_p3);

assign sext_ln1118_6_fu_14924_p1 = $signed(shl_ln1118_3_fu_14916_p3);

assign sext_ln1118_9_fu_14992_p1 = $signed(shl_ln1118_4_fu_14984_p3);

assign sext_ln1118_fu_14796_p1 = trunc_ln203_fu_14792_p1;

assign sext_ln708_10_fu_16003_p1 = $signed(trunc_ln708_29_reg_16519);

assign sext_ln708_11_fu_16006_p1 = $signed(trunc_ln708_30_reg_16524);

assign sext_ln708_12_fu_16009_p1 = $signed(trunc_ln708_32_reg_16534);

assign sext_ln708_13_fu_16012_p1 = $signed(trunc_ln708_37_reg_16559);

assign sext_ln708_14_fu_16015_p1 = $signed(trunc_ln708_42_reg_16584);

assign sext_ln708_15_fu_16018_p1 = $signed(trunc_ln708_43_reg_16589);

assign sext_ln708_16_fu_16021_p1 = $signed(trunc_ln708_44_reg_16594);

assign sext_ln708_17_fu_16024_p1 = $signed(trunc_ln708_45_reg_16599);

assign sext_ln708_18_fu_16027_p1 = $signed(trunc_ln708_46_reg_16604);

assign sext_ln708_19_fu_16030_p1 = $signed(trunc_ln708_56_reg_16654);

assign sext_ln708_1_fu_15976_p1 = $signed(trunc_ln708_4_reg_16389);

assign sext_ln708_20_fu_16033_p1 = $signed(trunc_ln708_57_reg_16659);

assign sext_ln708_21_fu_16036_p1 = $signed(trunc_ln708_58_reg_16664);

assign sext_ln708_22_fu_16039_p1 = $signed(trunc_ln708_60_reg_16674);

assign sext_ln708_23_fu_16042_p1 = $signed(trunc_ln708_61_reg_16679);

assign sext_ln708_2_fu_15979_p1 = $signed(trunc_ln708_5_reg_16394);

assign sext_ln708_3_fu_15982_p1 = $signed(trunc_ln708_8_reg_16409);

assign sext_ln708_4_fu_15985_p1 = $signed(trunc_ln708_9_reg_16414);

assign sext_ln708_5_fu_15988_p1 = $signed(trunc_ln708_10_reg_16424);

assign sext_ln708_6_fu_15991_p1 = $signed(trunc_ln708_16_reg_16454);

assign sext_ln708_7_fu_15994_p1 = $signed(trunc_ln708_22_reg_16484);

assign sext_ln708_8_fu_15997_p1 = $signed(trunc_ln708_23_reg_16489);

assign sext_ln708_9_fu_16000_p1 = $signed(trunc_ln708_28_reg_16514);

assign sext_ln708_fu_15973_p1 = $signed(trunc_ln_reg_16369);

assign shl_ln1118_10_fu_15841_p3 = {{tmp_13_fu_15811_p4}, {3'd0}};

assign shl_ln1118_11_fu_15879_p3 = {{tmp_13_fu_15811_p4}, {5'd0}};

assign shl_ln1118_1_fu_14815_p3 = {{trunc_ln203_fu_14792_p1}, {1'd0}};

assign shl_ln1118_2_fu_14904_p3 = {{tmp_2_fu_14873_p4}, {5'd0}};

assign shl_ln1118_3_fu_14916_p3 = {{tmp_2_fu_14873_p4}, {1'd0}};

assign shl_ln1118_4_fu_14984_p3 = {{tmp_3_fu_14964_p4}, {5'd0}};

assign shl_ln1118_5_fu_15002_p3 = {{tmp_3_fu_14964_p4}, {1'd0}};

assign shl_ln1118_6_fu_15030_p3 = {{tmp_3_fu_14964_p4}, {7'd0}};

assign shl_ln1118_7_fu_15125_p3 = {{tmp_4_fu_15078_p4}, {9'd0}};

assign shl_ln1118_8_fu_15137_p3 = {{tmp_4_fu_15078_p4}, {2'd0}};

assign shl_ln1118_9_fu_15516_p3 = {{tmp_s_fu_15479_p4}, {1'd0}};

assign shl_ln1118_s_fu_15601_p3 = {{tmp_1_fu_15554_p4}, {5'd0}};

assign shl_ln_fu_14803_p3 = {{trunc_ln203_fu_14792_p1}, {6'd0}};

assign sub_ln1118_1_fu_14996_p2 = ($signed(22'd0) - $signed(sext_ln1118_9_fu_14992_p1));

assign sub_ln1118_2_fu_15014_p2 = ($signed(sub_ln1118_1_fu_14996_p2) - $signed(sext_ln1118_10_fu_15010_p1));

assign sub_ln1118_3_fu_15042_p2 = ($signed(24'd0) - $signed(sext_ln1118_11_fu_15038_p1));

assign sub_ln1118_4_fu_15528_p2 = ($signed(18'd0) - $signed(sext_ln1118_27_fu_15524_p1));

assign sub_ln1118_5_fu_15613_p2 = ($signed(22'd0) - $signed(sext_ln1118_29_fu_15609_p1));

assign sub_ln1118_6_fu_15853_p2 = ($signed(20'd0) - $signed(sext_ln1118_37_fu_15849_p1));

assign sub_ln1118_7_fu_15891_p2 = ($signed(22'd0) - $signed(sext_ln1118_38_fu_15887_p1));

assign sub_ln1118_fu_14827_p2 = ($signed(sext_ln1118_1_fu_14811_p1) - $signed(sext_ln1118_2_fu_14823_p1));

assign tmp_10_fu_15629_p4 = {{data_V_read_int_reg[191:176]}};

assign tmp_11_fu_15695_p4 = {{data_V_read_int_reg[207:192]}};

assign tmp_12_fu_15753_p4 = {{data_V_read_int_reg[223:208]}};

assign tmp_13_fu_15811_p4 = {{data_V_read_int_reg[239:224]}};

assign tmp_14_fu_15907_p4 = {{data_V_read_int_reg[255:240]}};

assign tmp_1_fu_15554_p4 = {{data_V_read_int_reg[175:160]}};

assign tmp_2_fu_14873_p4 = {{data_V_read_int_reg[31:16]}};

assign tmp_3_fu_14964_p4 = {{data_V_read_int_reg[47:32]}};

assign tmp_4_fu_15078_p4 = {{data_V_read_int_reg[63:48]}};

assign tmp_5_fu_15165_p4 = {{data_V_read_int_reg[79:64]}};

assign tmp_6_fu_15227_p4 = {{data_V_read_int_reg[95:80]}};

assign tmp_7_fu_15289_p4 = {{data_V_read_int_reg[111:96]}};

assign tmp_8_fu_15351_p4 = {{data_V_read_int_reg[127:112]}};

assign tmp_9_fu_15417_p4 = {{data_V_read_int_reg[143:128]}};

assign tmp_s_fu_15479_p4 = {{data_V_read_int_reg[159:144]}};

assign trunc_ln203_fu_14792_p1 = data_V_read_int_reg[15:0];

endmodule //dense_latency_ap_fixed_ap_fixed_config2_0_0_0_0_0
